exchange2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('exchange/', include('exchangeapp.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

exchangeapp/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('detail/<str:stock_name>', views.detail_page, name='detail_page'),
    path('detail/<int:stock_id>/response', views.detail, name='detail'),
    path('', views.main_page, name='main_page'),
    path('main_course', views.main, name='main'),
    path('buy/<int:stock_id>/<int:user_id>', views.buy, name='buy'),
    path('sell/<int:stock_id>/<int:user_id>', views.sell, name='sell'),
    path('portfolio/', views.portfolio_page, name='portfolio'),
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # post views
    path('', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('money/<int:pk>', views.money, name='money'),
]

exchangeapp/models.py
from django.db import models

from users.models import CustomUser


class Stock(models.Model):
    name = models.CharField(max_length=4)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True,blank=True, default='')
    price = models.FloatField(default=1, null=True)


    def __str__(self):
        return self.name


class Portfolio(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, default='')
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, null=True, default='')
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0, null=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=3,verbose_name='стоимость', default=0, null=True)

exchangeapp/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
import requests
import time
from django.views.decorators.http import require_GET, require_POST
from users.forms import ValueForm
from .models import Stock, Portfolio


#Страница детального отображения акции с графиком
def detail_page(request, stock_name):
    form = ValueForm()
    stock = get_object_or_404(Stock, name=stock_name)
    url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol={}&interval=5min&apikey=X3X08NCFX3EY2HW3'
    response = requests.get(url.format(stock.name)).json()
    try:
        prices = response['Time Series (5min)']
    except KeyError:
        time.sleep(15)
        response = requests.get(url.format(stock.name)).json()
        prices = response['Time Series (5min)']
    price = prices[list(prices.keys())[0]][list(prices[list(prices.keys())[0]].keys())[3]] # выбирает последнюю обновленную цену
    stock.price = float(price)                                                             # и записывает её как настоящую цену
    stock.save()
    try:
        portfolio = Portfolio.objects.get(user=request.user, stock__name=stock_name)
        context = {'stock': stock, 'price': price, 'buy_form': form, 'sell_form': form, 'portfolio': portfolio}
    except Portfolio.DoesNotExist:
        context = {'stock': stock, 'price': price,'buy_form': form, 'sell_form': form}
    return render(request, 'exchangeapp/index.html', context)

#детальный ответ
@require_GET
def detail(request, stock_id):
    print('ФУНКЦИЯ СРАБОТАЛА')
    api_key = 'X3X08NCFX3EY2HW3'
    url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol={}&interval=5min&apikey=X3X08NCFX3EY2HW3'

    stock = get_object_or_404(Stock, pk=stock_id)

    all_stocks = []
    all_s = {}

    response = requests.get(url.format(stock.name)).json()
    print('респонз прошел')
    data_all = []
    for time, price in response['Time Series (5min)'].items():
        open = price['1. open']
        high = price['2. high']
        low = price['3. low']
        close = price['4. close']
        data = [time, float(low), float(open), float(close), float(high)]
        data_all.append(data)
        all_s.update({time: data})
        data_all.sort(reverse=False)
    return JsonResponse(data_all[40:], safe=False)

#главная страница
def main_page(request):
    a = []
    url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol={}&interval=5min&apikey=X3X08NCFX3EY2HW3'
    stocks = Stock.objects.all()
    for stock in stocks:
        print('-----------------------------------------------------------------------------------------------------------------------------------------')
        response = requests.get(url.format(stock.name)).json()
        try:
            price = response['Time Series (5min)']
        except KeyError:
            time.sleep(15)
            response = requests.get(url.format(stock.name)).json()
            price = response['Time Series (5min)']
        price = response['Time Series (5min)']
        last_r = response['Meta Data']['3. Last Refreshed']
        dict = {
            'name': response['Meta Data']['2. Symbol'],
            'price': price[last_r]['4. close'],
        }
        a.append(dict)
    context = {'all_info': a}
    return render(request, 'exchangeapp/main.html', context)

#главная страница, получение данных из API
@require_GET
def main(request):
        a = {}
        url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol={}&interval=5min&apikey=FJEPU2CGUIUM6BRG'
        stocks = Stock.objects.all().order_by('name')
        for stock in stocks:
            response = requests.get(url.format(stock.name)).json()
            print(response)
            price = response['Time Series (5min)']
            last_r = response['Meta Data']['3. Last Refreshed']
            dict = {
                'name': response['Meta Data']['2. Symbol'],
                'price': price[last_r]['4. close'],
            }
            a.update({response['Meta Data']['2. Symbol']: price[last_r]['4. close']})
        return JsonResponse(a)

#Покупка акций
@require_POST
def buy(request,stock_id,user_id):
    quantity = request.POST['value']
    stock = Stock.objects.get(pk=stock_id)
    user = request.user
    try:
        portfolio = Portfolio.objects.get(user=request.user, stock=stock)
    except Portfolio.DoesNotExist:
        portfolio = Portfolio.objects.create(user=request.user, stock=stock)
    if (float(user.money) - int(quantity)*float(stock.price)) < 0:
        return HttpResponse('На балансе не достаточно средств, пополните баланс:<ссылка на пополнение>')
    user.money = float(user.money) - int(quantity)*float(stock.price)
    user.save()
    portfolio.quantity = int(portfolio.quantity)+int(quantity)
    portfolio.total_price = float(portfolio.total_price)+float(stock.price)*int(quantity)
    portfolio.save()
    return redirect(detail_page, stock.name)


#Продажа акций
@require_POST
def sell(request,stock_id,user_id):
    quantity = request.POST['value']
    stock = Stock.objects.get(pk=stock_id)
    user = request.user
    try:
        portfolio = Portfolio.objects.get(user=request.user, stock=stock)
    except Portfolio.DoesNotExist:
        return HttpResponse('Вы продаете больше акций, чем покупаете')
    if (int(portfolio.quantity)-int(quantity)) < 0:
        return HttpResponse('Вы продаете больше акций, чем покупаете')
    user.money = float(user.money) + int(quantity)*float(stock.price)
    user.save()
    portfolio.quantity = int(portfolio.quantity)-int(quantity)
    portfolio.total_price = float(portfolio.total_price) - float(stock.price) * int(quantity)
    portfolio.save()
    return redirect(detail_page, stock.name)


#Страница с портфелем
def portfolio_page(request):
    total_price = 0
    portfolio = Portfolio.objects.filter(user=request.user)
    for port in portfolio:
        total_price += port.total_price
    context = {'portfolio_list': portfolio, 'total_price': total_price}
    return render(request, 'exchangeapp/prof.html', context)

exchangeapp/templates/exchangeapp/detail.html
<!DOCTYPE html>
{% load static %}
{% include "exchangeapp/navbar.html"%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>
<body>
    <script>

google.charts.load('current', {'packages':['corechart']});
google.charts.setOnLoadCallback(drawChart);

var Data = $.ajax({
  type: "GET",
  dataType: "json",
  url: '{% url 'detail' stock.id %}',
  async: false
}).responseText;
console.log(Data)

function drawChart() {
var data = google.visualization.arrayToDataTable($.parseJSON(Data), true);

var options = {
fontSize: 12,
legend:'none',
candlestick: {
fallingColor: { strokeWidth: 0, fill: '#a52714' }, // red
risingColor: { strokeWidth: 0, fill: '#0f9d58' }, // green

},
colors: ['#999']
};

var chart = new google.visualization.CandlestickChart(document.getElementById('chart_div'));
chart.draw(data, options);
}
</script>
<h4>Баланс:{{user.money}}</h4>
{{stock.name}}:{{price}}
    <h4>У вас: {{portfolio.quantity}}</h4>
    <h4>Общая стоимость: {{portfolio.total_price}}</h4>
<div id="chart_div" class="animate__animated animate__fadeInLeft" style="width: 100%; height:600px;"></div>

<!--    <form action="{% url 'buy' stock.id user.id %}" method="post">-->
<!--        <h1>Купить:</h1>-->
<!--         {% csrf_token %}-->
<!--        {{buy_form}}-->
<!--        <input type="submit" value="Купить">-->
<!--    </form>-->

<!--<form action="{% url 'sell' stock.id user.id %}" method="post">-->
<!--    <h1>Продать:</h1>-->
<!--         {% csrf_token %}-->
<!--        {{buy_form}}-->
<!--        <input type="submit" value="Продать">-->
<!--    </form>-->
<div class="container">
  <div class="row row-cols-2">
    <div class="col">
        <form action="{% url 'buy' stock.id user.id %}" method="post">
        <h1>Купить:</h1>
         {% csrf_token %}
        {{buy_form}}
        <input type="submit" value="Купить">
    </form>
</div>
    <div class="col">
        <form action="{% url 'sell' stock.id user.id %}" method="post">
    <h1>Продать:</h1>
         {% csrf_token %}
        {{buy_form}}
        <input type="submit" value="Продать">
    </form>
    </div>

  </div>
</div>
</body>
</html>

exchangeapp/templates/exchangeapp/index.html
<!DOCTYPE HTML>
<html lang="ru">
{% load static %}
{% include "exchangeapp/navbar.html"%}
<head>
  <title>{{stock.name}}</title>
  <meta charset="UTF-8">
  <meta name="description" content="Описание страницы" />
  <meta charset="utf-8" />

  <link  rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'exchangeapp/css/style.css' %}">
  <script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js"></script>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
      <script>

google.charts.load('current', {'packages':['corechart']});
google.charts.setOnLoadCallback(drawChart);

function drawChart() {
        var Data = $.ajax({
            type: "GET",
            dataType: "json",
            url: '{% url 'detail' stock.id %}',
            async: false
}).responseText;
        document.getElementById('price').innerHTML = Data.slice(-1).slice(3);
        console.log(Data);
        var data = google.visualization.arrayToDataTable($.parseJSON(Data), true);

        var options = {
        fontSize: 12,
        legend:'none',
        candlestick: {
        fallingColor: { strokeWidth: 0, fill: '#a52714' }, // red
        risingColor: { strokeWidth: 0, fill: '#0f9d58' }, // green

        },
        colors: ['#999']
        };

        var chart = new google.visualization.CandlestickChart(document.getElementById('chart_div'));
        chart.draw(data, options);
        }

        $(document).ready(function(){
        setInterval(drawChart,300000);
        });
</script>

</head>

<body>

<main>
    <section>
      <center><h1 class="animate__animated animate__fadeIn">{{stock.name}}</h1>
      <h3>Цена: {{price}}$</h3></center>
      <div class="graph">
        <div id="chart_div" class="animate__animated animate__fadeInLeft" style="width: 100%; height:600px;"></div>
      </div>
    </section>
    <center>
      <h4>У вас: {{portfolio.quantity}} шт.</h4>
        <h3>Общая стоимость: {{portfolio.total_price}}$</h3>
        <h3>Баланс: {{user.money}}$</h3>
    <h3 id="price">Цена: {{price}}$</h3>
    </center>

    <div class="container">
<div class="row row-cols-2">
<div class="col">
<form action="{% url 'buy' stock.id user.id %}" method="post">
{% csrf_token %}
{{buy_form.value}}
<button type="submit" class="btn btn-primary">Купить</button>
</form>
</div>
<div class="col">
<form action="{% url 'sell' stock.id user.id %}" method="post">

{% csrf_token %}
{{buy_form.value}}
<button type="submit" class="btn btn-primary">Продать</button>
</form>
</div>

</div>
</div>
</main>


</body>

</html>

exchangeapp/templates/exchangeapp/main.html
<!DOCTYPE html>
{% load static %}
{% include "exchangeapp/navbar.html"%}
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">


  <link  rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{% static 'exchangeapp/css/main-style.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@500&display=swap" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
  <script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js"></script>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>



  <title>StocKL</title>
</head>
<body>
  {% for info in all_info %}
    <div class="card">
    <div class="card-body">
    <center><h3 class="card-title">{{info.name}}</h3></center>
    <center><h4 class="card-text" data-name="{{info.name}}">{{info.price}}$</h4></center>
    <div class="boton"><a href="{% url 'detail_page' info.name %}" class="botn">Подробнее</a></div>
    </div>
    </div>
{% endfor %}
    <script>

function get_data() {
        $.ajax({
        url: '{% url 'main' %}',
        datatype: 'json',
        type: 'GET',
        success: function (data) {
             console.log(data);
             for (var key in data) {
             console.log(key);
             console.log(data[key]);
                document.querySelector(`[data-name='${key}']`).innerHTML = data[key];
                }
        }
    });
};
        $(document).ready(function(){
        setInterval(get_data,300000);
        });

</script>
</body>
</html>

exchangeapp/templates/exchangeapp/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'exchangeapp/css/navbar.css' %}">
    <link rel="shortcut icon" href="https://cdn-icons-png.flaticon.com/512/724/724811.png" type="image/x-icon">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main_page' %}">StocKL</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main_page' %}">Акции</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio' %}">Портфель</a>
            </li>
              <div id="logout">
              <li  class="nav-item">
              <a class="nav-link"  href="{% url 'users:logout' %}">Выйти</a>
            </li>
              </div>
          </ul>
        </div>
      </div>
    </nav>
  </header>
</body>
</html>

exchangeapp/templates/exchangeapp/portfolio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Баланс: {{user.money}}</h1>
<h2>Общая стоимость всех акций:{{total_price}}</h2>
{% for portfolio in portfolio_list %}
    <div>
        <h1>{{portfolio.stock}}</h1>
        <h4>{{portfolio.quantity}}</h4>
        <h4>Общая стоимость: {{portfolio.total_price}}</h4>
        </div>
{% endfor %}
</body>
</html>

exchangeapp/templates/exchangeapp/prof.html
<!DOCTYPE html>
{% load static %}
{% include "exchangeapp/navbar.html"%}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Портфель {{user.email}}</title>

  <link  rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'exchangeapp/css/prof.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@500&display=swap" rel="stylesheet">

  <script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js"></script>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>
<body>

  <div class="greeting">
    <center><h2>Здравствуйте, {{user.email}} </h2></center>
  </div>


  <div class="money">

    <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
      <div class="btn-group" role="group" aria-label="First group">
        <h3>Баланс: <b>{{user.money}}$</b></h3>
      </div>
      <div class="input-group">
        <a href="{% url 'users:money' user.id%}" class="botn"><center>Пополнить</center></a>
      </div>

    </div>
  </div>
  <div class="total_price">
  <center><h3>Общая стоимость всех акций: <b>{{total_price}}$</b></h3></center>
  </div>

<div class="table-KL">
  <table class="table table-hover">
    <thead>
      <tr class="pepp">
        <th scope="col"></th>
        <th scope="col">Название акции</th>
        <th scope="col">Количество</th>
        <th scope="col">Сумма</th>
      </tr>
    </thead>
    <tbody>
    {% for portfolio in portfolio_list %}
      <tr>
        <td></td>
        <td><a style="text-decoration: none; color: black;" href="{% url 'detail_page' portfolio.stock.name %}">{{portfolio.stock}}</a></td>
        <td>{{portfolio.quantity}}</td>
        <td>{{portfolio.total_price}}$</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>


</body>
</html>